name: 0. testen van acties

on:
  workflow_dispatch:
    inputs:
      Unit_test:
        description: 'Unit test oke?'
        required: True
      home:
        description: 'location'
        required: true
        default: 'The Octoverse'





jobs:
  stap1:
    runs-on: ubuntu-latest
    env:
      PROCEED: "ja" 
    steps:
#       - run: |
#           sudo /etc/init.d/mysql start

      - name: Niet akkoord
        if: false == ${{ github.event.inputs.Unit_test == env.PROCEED && github.event.inputs.home == env.PROCEED}}
        run: exit 1 
        
      - name: akkoord
#         if: ${{ github.event.inputs.Unit_test == env.PROCEED && github.event.inputs.home == env.PROCEED}}
        run: echo "stap 1"
        
      - name: Docker containers stoppen
#         if: ${{ github.event.inputs.Unit_test == env.PROCEED && github.event.inputs.home == env.PROCEED}}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}



#   stap2:
#     runs-on: ubuntu-latest
#     needs: ["stap1"]
#     steps:
#       - name: stap 2
#         run: echo "stap 2"






#       - name: Pauze
#         run: sleep 30s
#         shell: bash
# #Marketplace: https://github.com/marketplace/actions/wait-sleep
# # zet een pauze van een x aantal minuten in om vervolgens weer verder te gaan met de workflow.
    




#   Mergen_van_branches:
#     runs-on: ubuntu-latest
#     steps:

#       - name: chechout branches
#         uses: actions/checkout@v2

#       - name: Merge Master met Develop
#         uses: devmasx/merge-branch@v1.3.1
#         with:
#           type: now
#           from_branch: main
#           target_branch: Develop
#           github_token: ${{ github.token }}

#       - name: merge Issue met Develop
#         uses: devmasx/merge-branch@v1.3.1
#         with:
#             type: now
#             from_branch: Issue
#             target_branch: Develop
#             github_token: ${{ github.token }}
          
       
       
       
       
       
       
       


###ACTIE TESTEN: ALLEEN 1 SPECIFIEKE BRANCH UITCHECKEN MIDDELS DE ref FUNCTIE
#   checkout_branch:
#     runs-on: ubuntu-latest
#     steps:
    
#     - uses: actions/checkout@v2
#       with:
#         ref: 'Issue'










###JIRA TESTEN: MET AUTOMATISCHE MELDINGEN SCHRIJVEN IN ISSUE
#   Jira:
#     runs-on: ubuntu-latest 
#     steps:
    
#     - name: Inloggen Jira
#       uses: atlassian/gajira-login@master
#       env:
#         JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#         JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
# # marketplace: https://github.com/marketplace/actions/jira-login
    
    
#     - name: Jira Issue comment
#       uses: atlassian/gajira-comment@master
#       with:
#         issue: PO-54
#         comment: ${{ github.event.pusher.name }} "Unit test is uitgevoerd"
# # marketplace: https://github.com/marketplace/actions/jira-add-comment
