name: testfile 2

on:
#   workflow_dispatch:

  workflow_run:
    workflows: ["0. testen van acties"]
    types: [completed]
  
jobs:
#   test1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: stap 1
#         run: echo "stap 1"

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: succes 
        run: echo "Vorige run was succesvol"


#   on-failure:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       - name: Gefaald
#         run: echo "Vorige run is gefaald"
