name: testfile 2

on:
  workflow_dispatch:
      inputs: 
        SonarQUBE:
          description: 'Is de SonarQUBE test oke?'
          required: True
           
           
        OWASP:
          description: 'Is de OWASP test uitgevoerd?'
          required: True
  
  workflow_run:
    workflows: ["0. testen van acties"]
    types: [completed]
  
jobs:
  stap1:
    runs-on: ubuntu-latest
    steps:
      - name: stap 1
        run: echo "stap 1"
