name: testfile 2

on:
  workflow_run:
    workflows: ["0. testen van acties"]
    types: [completed]
  
jobs:
  stap1:
    runs-on: ubuntu-latest
    steps:
      - name: stap 1
        run: echo "stap 1"
