name: Demo SOLL ontwikkelstraat

on:
  workflow_dispatch:

jobs:
  Unit_testen_van_de_branch:
    runs-on: ubuntu-latest
    steps:
    
#     - name: chechout branches
#       uses: actions/checkout@v2

    - name: Uitvoeren van Unit test
      run: echo 'Unit test uitgevoerd'
      
      
      
      
  Merge_conflicten_vinden_1:
    needs: "Unit_testen_van_de_branch"
    runs-on: ubuntu-latest
    steps:
        
#       - name: chechout branche
#         uses: actions/checkout@v2
            
#       - name: Merge Conflict finder
#         uses: olivernybroe/action-conflict-finder@v2.0
        
      - name: merge conflict finder uitvoeren 
        run: echo "conflict finder utgevoerd"
              
              
              
              
  Develop_branch_updaten_met_master_branch:
    needs: "Merge_conflicten_vinden_1"
    runs-on: ubuntu-latest
    steps:

#       - name: chechout branches
#         uses: actions/checkout@v2

#       - name: mergen van Master_branch met de Develop_branch
#         run: echo 'Issue_branch gemerged met Develop_branch'

#       - uses: devmasx/merge-branch@v1.3.1
#         with:
#           type: now
#           from_branch: main
#           target_branch: Develop
#           github_token: ${{ github.token }}
          
      - name: Master_branch updaten met Develop_branch 
        run: echo "Develop_branch geupdatet met Master_branch"
              
              
              
              
  merge_conflicten_vinden_2:
    needs: "Develop_branch_updaten_met_master_branch"
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2
        
#       - name: Merge Conflict finder
#         uses: olivernybroe/action-conflict-finder@v2.0
        
      - name: merge conflict finder uitvoeren, 2e 
        run: echo "conflict finder utgevoerd, 2e"
          
    
    
    
  Bouwen_van_de_develop_branch_1:
    needs: "merge_conflicten_vinden_2"
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2
        
#       - uses: devmasx/merge-branch@v1.3.1
#         with:
#             type: now
#             from_branch: Issue
#             target_branch: Develop
#             github_token: ${{ github.token }}
            
      - name: mergen van Issue_branch met Develop_branch
        run: echo 'Issue_branch gemerged met Develop_branch'
    
    
    
    
  Bouwen_van_de_develop_branch_2:
    needs: "merge_conflicten_vinden_2"
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2
        
#       - uses: devmasx/merge-branch@v1.3.1
#         with:
#           type: now
#           from_branch: Issue1
#           target_branch: Develop
#           github_token: ${{ github.token }}
          
      - name: mergen van Issue_branch met Develop_branch
        run: echo 'Issue_branch gemerged met Develop_branch'
          
# marketplace: https://github.com/marketplace/actions/merge-branch
          
  
  
  
  SonarQUBE_test:
    needs: ["Bouwen_van_de_develop_branch_1", "Bouwen_van_de_develop_branch_2"]
    runs-on: ubuntu-latest
    steps:

#     - name: chechout branches
#       uses: actions/checkout@v2
        
#     - uses: kitabisa/sonarqube-action@master
#       with:
#         projectBaseDir: "/path/to/my-custom-project"
#         projectKey: "my-custom-project"
#         projectName: "my-custom-project-name"
#         projectVersion: "v0.0.1"

      - name: Uitvoeren van SonarQUBE
        run: echo 'SonarQUBE test uitgevoerd'

# marketplace: https://github.com/marketplace/actions/sonarqube-scan
  
  
  
  
  OWASP_test:
    needs: ["Bouwen_van_de_develop_branch_1", "Bouwen_van_de_develop_branch_2"]
    runs-on: ubuntu-latest
    steps:
        
#       - uses: zaproxy/action-full-scan@v0.2.0
#         with:
#           target: 'localhost:8080'

      - name: Uitvoeren van OWASP
        run: echo 'OWASP scan uitgevoerd'
          
# marketplace: https://github.com/marketplace/actions/owasp-zap-full-scan




  Component_test:
    needs: ["Bouwen_van_de_develop_branch_1", "Bouwen_van_de_develop_branch_2"]
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2

      - name: uitvoeren van component test
        run: echo 'Component test uitgevoerd'
    
    
    
    
  Deployment_van_Develop_branch_op_test_PRO:
    needs: ["SonarQUBE_test", "OWASP_test", "Component_test"]
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2

      - name: Deployemnt van de Develop_branch op de test omgeving
        run: echo 'Development_branch gedeployed op de test omgeving'
        
      - name: Run Smoke test op de test omgeving
        run: echo 'Smoke test uitgevoerd'




  Acceptatietest:
    needs: ["Deployment_van_Develop_branch_op_test_PRO"]
    runs-on: ubuntu-latest
    steps:
    
#       - name: tests
#         uses: joelwmale/codeception-action@master
# #           FRAMEWORK: laravel
# #           ENV_FILE: .env.test
          
# Supplying a framework & env file is not required. It will by default just run codeception from the vendor folder (composer storage).

      - name: Acceptatietest uitvoeren
        run: echo 'Acceptatietest uitgevoerd'
        
# https://github.com/marketplace/actions/codeception-action
      
        
        
        
  Regressietest:
    needs: ["Deployment_van_Develop_branch_op_test_PRO"]
    runs-on: ubuntu-latest
    steps:
#       - name: tests
#         uses: joelwmale/codeception-action@master
# #           FRAMEWORK: laravel
# #           ENV_FILE: .env.test

      - name: regressietest uitvoeren
        run: echo 'regressietest uitgevoerd'
        
        
        
        
  Gebruikerstest:
    needs: ["Deployment_van_Develop_branch_op_test_PRO"]
    runs-on: ubuntu-latest
    steps:

      - name: Gebruikerstest uitvoeren
        run: echo 'Gebruikerstest uitgevoerd'
        
        
        
  Merge_conflicten_vinden_3:
    needs: ["Acceptatietest", "Regressietest", "Gebruikerstest"]
    runs-on: ubuntu-latest
    steps:
        
#       - name: chechout branches
#         uses: actions/checkout@v2
            
#       - name: Merge Conflict finder
#         uses: olivernybroe/action-conflict-finder@v2.0
        
      - name: merge conflict finder uitvoeren 
        run: echo "conflict finder utgevoerd"
        
        
        
        
  Bouwen_van_de_Master_branch:
    needs: "Merge_conflicten_vinden_3"
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2
        
#       - uses: devmasx/merge-branch@v1.3.1
#         with:
#             type: now
#             from_branch: Develop
#             target_branch: main
#             github_token: ${{ github.token }}
            
      - name: mergen van Develop_branch met Master_branch
        run: echo 'Develop_branch gemerged met Master_branch'
        
        
        
        

  Deployment_van_Master_branch_op_PRO:
    needs: ["Bouwen_van_de_Master_branch"]
    runs-on: ubuntu-latest
    steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2

      - name: Deployemnt van de Master_branch op de Productie omgeving
        run: echo 'Master_branch gedeployed op de Productieo omgeving'
        
      - name: Run Smoke test op de productie omgeving
        run: echo 'Smoke test uitgevoerd'
