name: Deployment testen

on:
  workflow_dispatch:

jobs:
  Deployment_van_Develop_branch_op_test_PRO:
   runs-on: ubuntu-latest
   steps:
    
#       - name: chechout branches
#         uses: actions/checkout@v2

      - name: Deployemnt van de Develop_branch op de test omgeving
        run: echo 'Development_branch gedeployed op de test omgeving'
        
      - name: Run Smoke test op de test omgeving
        run: echo 'Smoke test uitgevoerd'
