name: 4. productie testen

on:
  workflow_dispatch:

jobs:
  
  Acceptatietest:
    runs-on: ubuntu-latest
    steps:
    
#       - name: tests
#         uses: joelwmale/codeception-action@master
# #           FRAMEWORK: laravel
# #           ENV_FILE: .env.test
          
# Supplying a framework & env file is not required. It will by default just run codeception from the vendor folder (composer storage).

      - name: Acceptatietest uitvoeren
        run: echo 'Acceptatietest uitgevoerd'
        
# https://github.com/marketplace/actions/codeception-action
      
        
        
        
  Regressietest:
    runs-on: ubuntu-latest
    steps:
#       - name: tests
#         uses: joelwmale/codeception-action@master
# #           FRAMEWORK: laravel
# #           ENV_FILE: .env.test

      - name: regressietest uitvoeren
        run: echo 'regressietest uitgevoerd'
        
        
        
        
  Gebruikerstest:
    runs-on: ubuntu-latest
    steps:

      - name: Gebruikerstest uitvoeren
        run: echo 'Gebruikerstest uitgevoerd'
