# Chechout v2, heeft meerdere varianten: https://github.com/marketplace/actions/checkout?version=v2.3.4

name: Script testing 

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ${BRANCH_NAME}
