name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: nelonoel/branch-name@v1.0.1
    # Use branch name for whatever purpose
    - run: echo ${BRANCH_NAME}
