name: Unit testen 

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  Unit_testen_van_de_branch:
    runs-on: ubuntu-latest
    steps:
    
#     - name: chechout branches
#       uses: actions/checkout@v2

    - name: Uitvoeren van Unit test
      run: echo 'Unit test uitgevoerd'
